<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class SupportPinController extends Controller
{
    public function store(Request $request): RedirectResponse
    {
        $user = $request->user();
        $activeWorkspaceId = $request->session()->get('active_workspace_id');

        if (!$activeWorkspaceId) {
            return back()->with('error', 'You must have an active workspace to request support.');
        }

        $workspace = $user->workspaces()->find($activeWorkspaceId);
        
        if (!$workspace || $workspace->pivot->role !== 'owner') {
            return back()->with('error', 'Only Workspace Owners can authorize Support PINs.');
        }

        $pin = str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);
        
        $user->forceFill([
            'support_pin' => $pin,
            'support_pin_expires_at' => now()->addHours(24),
        ])->save();

        Log::info("Support PIN generated by Owner ID: {$user->id} for Workspace: {$workspace->name}");

        return back()->with('success', 'Support PIN generated successfully.');
    }
}